### ISSUE TITLE
LX200 Classic INDI Driver ethernet issue

### ISSUE THREAD

**Issue by AnakChan** [rkaczorek/astroberry-server#101]
I've got an issue where trying to switch from serial to ethernet on the LX Classic driver does nothing. It stays on Classic. Trying the LX200 Basic on the other hand operates as expected. I'm not certain fo the differences between the LX200 Classic and LX200 Basic if I can just use the LX200 Basic as an interim alternative.

**Comment by rkaczorek** [comment]
This must be reported on https://github.com/indilib/indi-3rdparty
