### ISSUE TITLE
Can't edit files in root to change settings for GPS hat

### ISSUE THREAD

**Issue by kattzx3** [rkaczorek/astroberry-server#106]
Hello,

Sorry, can't find the answer.  Trying to edit \etc\default\gpsd to use GPS HAT and no edits are allowed.

Been working on this and cruising the web for a week, tried numerous things, please help.

Thanks.

Kevin

**Comment by rkaczorek** [comment]
You need to edit the file as a superuser. Use sudo command in front of your favorite file editor

**Comment by kattzx3** [comment]
OK.  Didn't know that, sorry.  Used sudo nano path/to/file and worked great!

Thanks so much - sorry for my ignorance!

Kevin
