### ISSUE TITLE
Astroberry crashing with ZWO Asi2600 MC Pro camera

### ISSUE THREAD

**Issue by Lucanerli** [rkaczorek/astroberry-server#113]
Hi,
thanks for the great work on INDI
I am an amateur astronomer I would like to use Raspberry Pi3b with Kstars-Ekos on my setup but I find a problem of which I don't understand the origin. When I take a photo with my ZWO Asi 2600 MC Pro the system locks on the fits viewer. Are you aware of the problem? Could it depend on the driver, or could it be due to the low power of the RPI3?
regards Luca

**Comment by rkaczorek** [comment]
I think it can be caused by limited RAM on RPI3. Disable debayering and/or enable limited resources mode in KStars setting.

**Comment by Lucanerli** [comment]
Thanks
Nerli Luca
lunerli54@gmail.com
GAMP Gruppo Atrofici Montagna Pistoiese
3357286011

**Comment by bekro** [comment]
The camera works perfect on the RPi4 (8GB version).
