### ISSUE TITLE
Advertise HTTP service properly

### ISSUE THREAD

**Issue by marcocipriani01** [rkaczorek/astroberry-server#118]
Hello,
I had some troubles discovering the Astroberry service (`astroberry.local`) from some devices, Android in particular. I solved it by adding the following file: `/etc/avahi/services/astroberry.service`

```
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">%h</name>
<service>
<type>_http._tcp</type>
<port>80</port>
</service>
</service-group>
```

And then running `sudo systemctl restart avahi-daemon.service`. Can you add this file in the next Astroberry release?
Reference: [How to use Avahi to advertise an HTTP service](https://sosheskaz.github.io/tutorial/2016/09/26/Avahi-HTTP-Service.html)

Kind regards,
Marco Cipriani

**Comment by rkaczorek** [comment]
Thanks for the fix. I will add this config in the next release

**Comment by rkaczorek** [comment]
Implemented in [astroberry-server-sysmod](https://github.com/rkaczorek/astroberry-server-sysmod/commit/2b3df4811b5251d0d60df8cb669c262d50cd0b39) on the 1st of March
