### ISSUE TITLE
Renaming astroberry user

### ISSUE THREAD

**Issue by pleiades-coram** [rkaczorek/astroberry-server#132]
Hi,

I want to rename the "astroberry" user's name but seems blocked even when booting from root.  I can just rename "pi" user.

When booting from text console with native Raspberry OS, I can rename "pi" when logging from root but it's not possible when using Astroberry OS.

I was using **usermod -l newname astroberry** to rename user's name and **usermod -m -d /home/newname newname** to move the astroberry content to the newname folder.

With native Raspberry pi OS it's all working except with Astroberry OS.

Any clues?

Yves

**UPDATE:  It's always the same...I asked for help and find the answer later... :-)

I needed to put an "S" at the end of the following line to boot in safe mode.  After doing usermod command twice to rename and move the folder.

/boot/cmdfile.txt --> console=tty1 root=PARTUUID=ef82d6f4-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait S**

**Comment by rkaczorek** [comment]
Glad you auto-solved this ;-)
Please close the issue if everything is fine
