### ISSUE TITLE
Error during Update & Upgrade

### ISSUE THREAD

**Issue by Sportfan1969** [rkaczorek/astroberry-server#136]
During the apt upgrade && apt update && apt dist-upgrade process, I receive an error "Failed building wheel for pyindi-client"
Then it rolls back the install of the pyindi-client stating "failed with error code 1 in /tmp/pip-install-72jL9rv3/pyindi-client/"

Any assistance would be greatly appreciated.

Thanks

**Comment by rkaczorek** [comment]
You should address this request to pyindi-client project
