### ISSUE TITLE
ZWO AsiStudio

### ISSUE THREAD

**Issue by luzik** [rkaczorek/astroberry-server#150]
There is Linux package with bunch of astrophotography apps. Don't know if anyone is allowed to redistribute this, but would be nice to have it packaged in astroberry.

**Comment by rkaczorek** [comment]
How AsiStudio is licensed?

**Comment by luzik** [comment]
I believe it's same as SDK

**Comment by rkaczorek** [comment]
I will leave it to users to decide if they want to install this package or not.
