### ISSUE TITLE
INDI Driver EQMod Mount crashed. Restart it ?

### ISSUE THREAD

**Issue by BeppeTemp** [rkaczorek/astroberry-server#157]
Hi everyone.

I am having this problem with EQMod Mount drivers. The problem occurs on a 2 GB Raspberry Pi 4 with a clean and updated installation as per documentation, I noticed that the error occurs only when astroberry is installed on an SSD connected to the Rapberry USB and not when it is installed on a SD card. Some idea ? Mi mount is an EQR6-PRO

thanks

**Comment by rkaczorek** [comment]
Could you test if it happens when SSD is connected to USB 2.0 instead USB 3.0?
