### ISSUE TITLE
Screen resolution unusable - cannot recover

### ISSUE THREAD

**Issue by Lightwel** [rkaczorek/astroberry-server#160]
Hi Radek

Weird and new problem re screen resolution on my 8Gb Pi4B.   

I normally boot Astroberry from SSD and somehow have managed to achieve a screen resolution which fills my 1920x1280 display with about 1/16th of the full desktop image - so greatly magnified that it is effectively unusable.   I can view either via browser or VNC but cannot resize - I can make the whole image bigger or smaller, but can not achieve more desktop real estate within the image.  I can't for instance see any dialogue boxes eg the OK box when trying to reset screen resolution in preferences.

As far as I can tell using terminal, my /boot/config.txt file is normal. By normal I mean the same contents (and comments) as the /boot/config.txt file on my SD card, which boots normally,  (Using the SSD, Terminal autowraps the text to the window which means it is readable - probably from across the room!).  I could be wrong about the contents - is there anything in particular I should be looking for?

Unfortunately, I cannot just reflash the SSD as that also contains a bunch of extras which I have not backed up to the SD card (oops).

I got into this mess trying to resize the desktop window to fill my screen window (browser or VNC) without blanking round the edges.  Quite a bit of the actual app window (eg Firecapture) was being lost, though as per above I could resize the whole window, but not get any greater coverage of the underlying app.

Any ideas how this might have happened and how to get out of it?   

Many thanks

R

**Comment by Lightwel** [comment]
PS should also have said that the issue persists when running with a screen plugged into the pi - ie this is not a browser or VNC issue it's a proper pi problem!

Tks

R

**Comment by rkaczorek** [comment]
You can set resolution by running raspi-config from terminal

**Comment by Lightwel** [comment]
Thanks.  

But I can’t use the raspi-config dialogue because I can only see a small portion of it.

Can I set resolution from a command prompt alone? 

BTW afaik the resolution is already set to FHD and config.txt seems to support this : however, what should config.txt say (to be certain it’s correct)? 

Tks R

**Comment by rkaczorek** [comment]
You can connect to your raspberry pi terminal via SSH. To do so use any SSH client e.g. PuTTY
Default resolution settings in config.txt are:
```
hdmi_force_hotplug=1
hdmi_group=2
hdmi_mode=82
````

**Comment by Lightwel** [comment]
Thanks - I've managed to achieve a usable desktop  by booting from SD card and opening the SSD /boot.config.txt in File Explorer.  

The SSD config.txt was not in fact the same as the SD, so I changed it to read the same.  

This is what it reads now and what it did before (when I started this post):
``
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
disable_overscan=1 **NOTE WAS =0**

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
framebuffer_width=960 **NOTE WAS A NUMBER IN THE 200's**
framebuffer_height=540 **NOTE WAS A NUMBER IN THE 100'S**

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=2
#hdmi_mode=82

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
enable_uart=1 **NOTE WAS =0**
gpu_mem=128
#hdmi_force_hotplug=1
#hdmi_group=2
#hdmi_mode=82
dtparam=i2c_arm=on
dtparam=spi=on
dtparam=audio=on
enable_uart=1 **NOTE WAS =0**
gpu_mem=128
#hdmi_force_hotplug=1
#hdmi_group=2
#hdmi_mode=82
dtparam=i2c_arm=on
dtparam=spi=on
dtparam=audio=on
enable_uart=1 **NOTE WAS =0**
gpu_mem=128
scaling_kernel=8
``
So I am now back in the situation where I cannot see the whole astroberry desktop (whether connected directly to a monitor, or viewing through browser or VNC).   The display is 1920x1080 in each case.  

Tks
 
R
