### ISSUE TITLE
iOptron device in EKOS always uses iPolar hardware instead?

### ISSUE THREAD

**Issue by dbadavekc** [rkaczorek/astroberry-server#161]
When selecting the iGuider as the guider on a CEM70G, the actual hardware that's used is always iPolar.
On a whim, I tried swapping iGuider for iPolar as a device, but iPolar was always chosen.

Not sure how to manually configure EKOS to use the correct device - any help is greatly appreciated!

<img width="801" alt="image" src="https://user-images.githubusercontent.com/27701673/138101052-1fabb902-d3aa-4bf2-8fb5-8f97edaaa1c7.png">
<img width="838" alt="image" src="https://user-images.githubusercontent.com/27701673/138100542-e9dc4d10-5255-4e12-a2a0-936b6c5357cb.png">
<img width="820" alt="image" src="https://user-images.githubusercontent.com/27701673/138100776-235ee5d0-3c59-4fdd-a891-6b461518d545.png">

**Comment by rkaczorek** [comment]
This should be posted to https://github.com/indilib/indi-3rdparty/issues

**Comment by dbadavekc** [comment]
I posted it there. Thanks!
