### ISSUE TITLE
File Folders to Backup

### ISSUE THREAD

**Issue by bbillp** [rkaczorek/astroberry-server#167]
Which folders are the Astroberry/KSTARS/EKOS and system file folders names to backup to external HD?   So far I backed  home, etc, usr, bin and libs.   I want to make sure Astroberry related configuration files are backed up.

**Comment by jscheidtmann** [comment]
Settings and even astrometry data files are stored in /home/Astroberry/.local, .indi, .gphoto, etc. and /etc so given your backup config you should be done. The litmus test of every backup is doing a successful restore: So practice that. Do this at your own risk. You have been warned.

The recommended way - I believe - is to clone the SDcard using the SD copy tool available from the menu. Plug-in a SDCard reader and a new SDCard, then copy the whole thing over. The pro of that is, that you‘ll be ready to continue out in the field, if the card physically breaks and you‘ll only loose some data and not the night. (And it will some day, given Murphy‘s law).

**Comment by jscheidtmann** [comment]
Also check: https://github.com/rlancaste/AstroPi3/blob/master/backupOrRestore.sh

**Comment by bbillp** [comment]
Thank you for the information on the backup info and script, looks good..  /home has been backed up on this Ubuntu system while backup SD cards have secured the Raspberry Pi system.    tnx
