### ISSUE TITLE
Ekos crash (Eqmod)

### ISSUE THREAD

**Issue by Lorbane** [rkaczorek/astroberry-server#171]
Found a crash issue with newest release of the indi-eqmod driver, specifically indi-eqmod 1.0-9 armfh.deb. Upon trying to connect the mount it would instantly crash both ekos and kstars. No matter what ports I used the crash happened 100% of the times, sometimes even showing a driver crash message. Resolved by downgrading to to 1.0-8.

**Comment by rkaczorek** [comment]
Make sure your main indi library is in the latest version (1.9.3). You can verify this by running `indiserver`
