### ISSUE TITLE
Ekos live demands username/password. Rejects what I provide

### ISSUE THREAD

**Issue by stevecoh1** [rkaczorek/astroberry-server#184]
Where is the Ekos Live password set? What is the default? How may I change it? I'm already logged in to astroberry.

**Comment by rkaczorek** [comment]
Ekos LIve if only for Stellarmate users. Astroberry does not support it

**Comment by stevecoh1** [comment]
> Ekos LIve if only for Stellarmate users. Astroberry does not support it

Thanks
