### ISSUE TITLE
Kernel Panic on boot up: 'not syncing: No working init found.'  Help!

### ISSUE THREAD

**Issue by aschmeelk** [rkaczorek/astroberry-server#22]

**Comment by aschmeelk** [comment]
This is on a Raspberry Pi 3+ b, 64 gb sd card, 2.5Amp power supply.

**Comment by rkaczorek** [comment]
Reflash SD card. It looks like major filesystem issue.

**Comment by aschmeelk** [comment]
I've reflashed it multiple times, same issue each time. I've flashed it on an Ubuntu machine, a mac and a pc. no difference. also used 2 different sd cards. I'm at a loss unless it has to do with the size of the card itself.

**Comment by aschmeelk** [comment]
Solved. You were right, I bought a new sd card and flashed it, now it's booting.
