### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by gajjer** [rkaczorek/astroberry-server#26]
when I launch Firefox it reports an error immediately. The error is 
We're sorry
Firefox had a problem and crashed
I tried to update Firefox but it reported that I had the latest version

**Comment by HoudayerPierre** [comment]
Hello, you can try to install chromium it works.
`sudo apt-get install chromium-browser`

**Comment by rkaczorek** [comment]
It is Ubuntu Mate 16.04 specific issue. It will be ok in the next release based on Ubuntu Mate 18.04
