### ISSUE TITLE
Firefox crashed at start

### ISSUE THREAD

**Issue by starhopper-de** [rkaczorek/astroberry-server#27]
Hello,
I tried the astroberry today. It is a great project. I like it. 
There is small issue, sometimes I need firefox for internet downloads or to check my mail.
Firefox is crashing right after clicking the symbol. If you do not think that is related to astroberry, close this issue.
![astroberry](https://user-images.githubusercontent.com/44210083/58383059-4fc9dd80-7fd2-11e9-90f3-5666f70c46ba.jpg)

**Comment by rkaczorek** [comment]
This is related to Ubuntu Mate 16.04 - see this issue https://github.com/rkaczorek/astroberry-server/issues/26

**Comment by starhopper-de** [comment]
Thanks for the reply
