### ISSUE TITLE
Raspberry pi 4

### ISSUE THREAD

**Issue by DariuszFirek** [rkaczorek/astroberry-server#29]
Is there any way to run astroberry on RPi 4? The performance gain, RAM, plus USB3 is a nice addition.

**Comment by rkaczorek** [comment]
AFAIK the current version (1.1.0) does not support RPi 4. I haven't tested it myself. RPi 4 will be supported in the next release.

**Comment by schreiberste** [comment]
Any news on this?
Astroberry is awesome, but I had some out-of-memory crashes while converting RAW NEF images to FITS and also the overall performance (kstars + ekos, plate solving...) could really use a little extra boost from the more potent hardware!

**Comment by rkaczorek** [comment]
Version 2.0.0 should be available soon. It's in the final tests phase

**Comment by schreiberste** [comment]
Exciting :)
Thanks a lot!

**Comment by rkaczorek** [comment]
Releasing today
