### ISSUE TITLE
Bluetooth timeout

### ISSUE THREAD

**Issue by gvandela** [rkaczorek/astroberry-server#30]
I installed a bluetooth serial port module in my mount and this was working flawless with INDI on a raspberry pi zero w running raspbian. However, using the astroberry image, I get timeout errors and I cannot get my mount to do anything.
I'm having a hard time finding any info on this issue and I'm stuck. Is this a known issue with the particular version of Ubuntu Mate? Any suggestions on what I could try next?

EDIT: I am able to connect to my mount, but soon after connecting, I get timeout errors and no commands seem to make it to my mount.

**Comment by gvandela** [comment]
I started from scratch with Ubuntu Mate 18.04 and got my mount to respond, no more timeout errors. Maybe it with the Ubuntu Mate version used on the astroberry image?

**Comment by rkaczorek** [comment]
Version 1.1.0 is based on Ubuntu Mate 16.04 Desktop. Ubuntu Mate 18.04 is still beta release. I'm still waiting on the stable version. What version of Raspberry Pi are you using? By any chance is it 3B+? If so I would not be surprised with BT problems. It work for me, but for many people doesn't.

**Comment by gvandela** [comment]
I am indeed using a 3B+. Thank you for your confirmation!
