### ISSUE TITLE
Lost WLAn Accesspoint

### ISSUE THREAD

**Issue by fohnbit** [rkaczorek/astroberry-server#31]
Hello,

I changed the language and clicked on the WLAN icon in Mint ... I thought I need to set the Access Point data.
But now the RPI don´t send the WLAN "astroberry" anymore.

How can I restore this?

Thank you!

**Comment by rkaczorek** [comment]
Well,I don't know what you really changed. Try using astroberry_vap [start|stop|status] in terminal.

**Comment by fohnbit** [comment]
Hello,

its working now again. Thank you!

**Comment by rkaczorek** [comment]
Great to hear this! Clear skies!
