### ISSUE TITLE
GPS panel reload (aka right click "reload" - same as F5 on Normal web browser) problem

### ISSUE THREAD

**Issue by cstachon** [rkaczorek/astroberry-server#39]
Hi ,

Slightly different but if the GPS MAP disappears you can get it back by doing a "reload" or F5 - this is ok if you are connected via std browser to <IP>:8625 - works ok.

If you do the same via the GPS panel it disconnects NOVNC - in my book a bug :-)

**Comment by rkaczorek** [comment]
It's a feature not a bug ;-) Refreshing the whole page disconnects socket connection to VNC server.
However you can reload panel itself - right click menu in the panel content gives you option to "reload this frame only"

**Comment by cstachon** [comment]
Ok Reload frame will do
