### ISSUE TITLE
question not a problem :-)

### ISSUE THREAD

**Issue by cstachon** [rkaczorek/astroberry-server#43]
Radek,
Indiserver started via the panel seems to use a PIPE(/tmp/indififo for communication with drivers ?

Does this mean the astroberry indi drivers are special in any way or is this something indi drivers have always been able to do.

Does this give any advantages?

Just being nosey :-)

**Comment by cstachon** [comment]
forget it i found the -f parameter for indiserver - doh

**Comment by rkaczorek** [comment]
Yes, this functionality has been around for a long time. That's how web-indi starts all the drivers. This way you can start/stop/restart a single driver while indiserver is up and running. Very useful feature
