### ISSUE TITLE
astroberry-server_2.0.0.img

### ISSUE THREAD

**Issue by THX59** [rkaczorek/astroberry-server#45]
Hi,
I'have just copied astroberry-server_2.0.0.img on a Scandisk Ultra 16 Gb + RPI3B.
There is no wifi hotspot so, nothing possible to do.
Thanks to help me.
Richard

**Comment by rkaczorek** [comment]
How did you copy it to the SD card? Have you connected it to screen with HDMI to check if it boots?

**Comment by THX59** [comment]
I have copied again the image and the hotspot works now.
Thanks for reactivity
