### ISSUE TITLE
Web VNC

### ISSUE THREAD

**Issue by porkyhttp** [rkaczorek/astroberry-server#50]
I installed the astroberry2 image, but vnc is not accessible via web, it says FAILED TO CONNECT, but it works if i use the vnc client from my pc or tablet

**Comment by rkaczorek** [comment]
This happens if you connect via **http**://astroberry.local and have you password remembered in your browser. Connect via **https**://astroberry.local or clear cookies before reconnecting via http

**Comment by porkyhttp** [comment]
Ok I will check it  this evening
