### ISSUE TITLE
QHY Cameras not working

### ISSUE THREAD

**Issue by sonny486** [rkaczorek/astroberry-server#54]
QHY cameras were working before the latest update.  Now QHY 163M does not work now.

:-(

**Comment by sonny486** [comment]
From Indilib.org:

It is related to last update of libqhy... Please downgrade the library by running:
wget https://www.astroberry.io/repo/pool/main/libq/libqhy/libqhy_6.0.5-2_armhf.deb
sudo dpkg -i libqhy_6.0.5-2_armhf.deb

**Comment by sonny486** [comment]
BTW Thanks for your hard work on this!   I love this system, made my imaging so much easier!  Thanks again.

**Comment by rkaczorek** [comment]
Please downgrade the library by running:
`wget https://www.astroberry.io/repo/pool/main/libq/libqhy/libqhy_6.0.5-2_armhf.deb
sudo dpkg -i libqhy_6.0.5-2_armhf.deb`

**Comment by sonny486** [comment]
Thanks, I have done that.  I didn't realize it was you who responded in Indilig.org.  Thanks.  It works great now!   I do appreciate your work.
