### ISSUE TITLE
oacapture fails to start

### ISSUE THREAD

**Issue by setnes** [rkaczorek/astroberry-server#56]
```
$ oacapture 
oacapture: error while loading shared libraries: libqhyccd.so.6: cannot open shared object file: No such file or directory
```

Is this an astroberry issue, or is it something upstream?

**Comment by rkaczorek** [comment]
This is related to upstream libqhy libraries updated. Oacapture needs to be updated on astroberry to use the latest libqhy. In the meantime you can apply this workaround:
`sudo ln -s /usr/lib/arm-linux-gnueabihf/libqhyccd.so /usr/lib/arm-linux-gnueabihf/libqhyccd.so.6`

**Comment by setnes** [comment]
The workaround allows me to launch Oacapture.  Thanks.

**Comment by rkaczorek** [comment]
Oacapture 1.7.0 has been just released, which fixes this bug
