### ISSUE TITLE
Black Screens

### ISSUE THREAD

**Issue by gbkelley** [rkaczorek/astroberry-server#6]
Initial black screen issues, reburned SD card
VNC and https OK
expanded filesystem and rebooted, VNC black screen and https immediately disconnected after connect
ssh into RasPi and rebooted
now VNC and https seem OK

**Comment by rkaczorek** [comment]
The root cause of this issue is unknown and I cannot trace it down. Apparently removing /home/astroberry/.Xauthority file and rebooting helps.

**Comment by rkaczorek** [comment]
Removed in v2.0.0
