### ISSUE TITLE
Should firecapture be added to default installation?

### ISSUE THREAD

**Issue by GrabzIt** [rkaczorek/astroberry-server#63]
It seems firecapture is now compatible with the pi. So would it be a good idea to have this on astroberry by default it seems that many people are manually installing it.

It would probably be a good tool to have on there as firecapture is great for planetary.

**Comment by rkaczorek** [comment]
This is a great tool indeed. However it cannot be added to astroberry by default as for now. Distribution is prohibited by license agreement. I will try to get the permission of the author.

**Comment by rkaczorek** [comment]
FireCapture in the house! Now you can install it from official astroberry repo.
Run: sudo apt install firecapture

**Comment by GrabzIt** [comment]
That's awesome thanks!!

**Comment by spoupart** [comment]
I have this error : E: Unable to locate package firecapture 
when i run: sudo apt install firecapture

**Comment by ManuelAstro** [comment]
Thanks so much for your work @rkaczorek, I’ve installed the package from the repo but I can’t find the app to be launched.
