### ISSUE TITLE
wlan config gui not working

### ISSUE THREAD

**Issue by error400** [rkaczorek/astroberry-server#7]
Hi I just donwnloaded AstroBerry and now I have the problem that the WLANCongig-gui has no Text Input for my wlan configuration.

**Comment by error400** [comment]
Still can't connect to my local WLAN, any suggestions?

**Comment by error400** [comment]
Now it is working. Had to change the script in /usr/local/bin

`
INPUT=$(zenity --forms --title="Configure WLAN" \
	--text="Enter information about WLAN network." \
	--separator="," \
	--add-entry="Network name" \
	--add-entry="Password" 2>/dev/null)

  SSID=$(awk -F, '{print $1}' <<<$INPUT)
  PSK=$(awk -F, '{print $2}' <<<$INPUT)
`

**Comment by rkaczorek** [comment]
Fixed in version 1.1.0
