### ISSUE TITLE
Remote shutter

### ISSUE THREAD

**Issue by FredoTheGreat** [rkaczorek/astroberry-server#72]
Hi Can you change the setup screen so that it saves the /dev/ttyUSB0 in the remote shutter setting on the gphoto ccd driver? rather than have to put it in every time?
also
there is a bug when you use this in that it does long exposure ok but if it has done a short exposure first ie when focusing it holds the camera in PC mode so then the long exposure shutter gets ignored by the camera.
many thanks

**Comment by rkaczorek** [comment]
This applies to gphoto ccd driver, not Astroberry.
Please file an issue here: https://github.com/indilib/indi-3rdparty
