### ISSUE TITLE
System boot partition too small

### ISSUE THREAD

**Issue by peterstellar** [rkaczorek/astroberry-server#8]
Hi Rkaczorek,

This project looks great, thank you for all your hard work.
I have done the install and updated the app but when I run Software Updater for the system I get "Not enough free disk space" error message. The current image has 63Mb for the Boot Sector but needs about 67Mb for the latest software setup. My resizing of the boot sector with Gparted has failed several times. Is there a simple solution to this?
![screenshot at 2018-09-12 01-18-39](https://user-images.githubusercontent.com/43189788/45393282-be206880-b61a-11e8-80fa-0c2b34efe12e.png)

Thanks Peter

**Comment by peterstellar** [comment]
While the issue is not with Astroberry Server, as soon as someone downloads Astroberry, installs it and does a system update they're likely to encounter this problem, using the current image.
I tried the SD card partition resize again (on my notebook) using Gparted with the same result.
There are a couple more screenshots attached if they help, along with the partition check file
![screenshot at 2018-09-13 19-10-32](https://user-images.githubusercontent.com/43189788/45483160-44f65200-b78f-11e8-9b07-21f1c2df6e41.png)
![screenshot at 2018-09-13 19-40-50](https://user-images.githubusercontent.com/43189788/45483163-458ee880-b78f-11e8-8786-0fc1ee40dd8e.png)
[Gparted Details.txt](https://github.com/rkaczorek/astroberry-server/files/2378904/Gparted.Details.txt)
If you think this problem may be a wider issue, would you please consider increasing the size of the boot partition on your image so that it is less likely to happen again. If it is just me, then I'll select the updates I think I'll need and go with that.
Thanks for your prompt reply and consideration.

**Comment by rkaczorek** [comment]
I cannot figure out why the error occurs while resizing the partition. I would recommend you partition a SD card manually - just create boot partition and root partition setting whatever size you want, name the partitions, create file systems on the partitions (fat16 on boot, ext2 on root), set the partition flags, copy the files from original Astroberry Server partitions. This will remove the issue.
The next release of Astroberry Server will address this.

**Comment by rkaczorek** [comment]
Fixed in version 1.1.0

**Comment by peterstellar** [comment]
Thank you for the update and all your help. I downloaded the image
this morning and have it running well. Regards Peter

----- Original Message -----
