### ISSUE TITLE
indi-full requires indi-pentax

### ISSUE THREAD

**Issue by setnes** [rkaczorek/astroberry-server#80]
Apt failed to upgrade indi-full.  It is depending on indi-pentax... which is not available.

The following packages have unmet dependencies:
 indi-full : Depends: indi-pentax but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by rkaczorek** [comment]
Thanks for reporting this. FIXED

**Comment by setnes** [comment]
Thanks!  :)
