### ISSUE TITLE
QHY 5III 462 not yet supported

### ISSUE THREAD

**Issue by MLKutzke** [rkaczorek/astroberry-server#87]
I just received the new qhy camera 462 but it is not yet recognized by the astroberry.
There seems to be a new Recent driver available from qhy that supports it.

I am Using Astroberry 2.0.3 on rpi 4b.
-Mike

**Comment by rkaczorek** [comment]
Thanks for reporting. I'm planning updates in a couple of days. I will check QHY driver status.

**Comment by rkaczorek** [comment]
QHY drivers has been updated. Please upgrade your system and report back.

**Comment by MLKutzke** [comment]
Success!
Just plugged it in, restarted the RPI4 after the update and it was recognized!
As I am typing here it is now taking the first (dark) frames (since it is cloudy it wont see first light outside tonight...).
I will report if I run into any additional issues - but this one can be closed.
-Mike
