### ISSUE TITLE
Astroberry Geographical Location

### ISSUE THREAD

**Issue by Avocette99** [rkaczorek/astroberry-server#9]
I have just started operating Astroberry as an astrophotography web server on a RPi 3 B+ and I note that the geographical information seems to be locked to Warsaw, Poland and the time and calendar date remain in Polish language and start in 2016. Am I missing something essential in my configuration options?

**Comment by Avocette99** [comment]
I have just started operating Astroberry as an astrophotography web server on a RPi 3 B+ and I note that the geographical information seems to be locked to Warsaw, Poland and the time and calendar date remain in Polish language and start in 2016. Am I missing something essential in my configuration options?

**Comment by rkaczorek** [comment]
Why don't you change your regional settings?
