### ISSUE TITLE
oaCapture not supporting Altair cameras anymore

### ISSUE THREAD

**Issue by GrabzIt** [rkaczorek/astroberry-server#98]
Hi,

I recently upgraded to 2.0.3 of Astroberry but oaCapture seems to have removed support for my Altair camera!

Please can version 1.6.0 be added back to the repository? So I can revert the update?

Kind Regards

Dominic

**Comment by rkaczorek** [comment]
You can manually download and install previous versions from https://www.astroberry.io/repo/pool/main/o/oacapture/

**Comment by GrabzIt** [comment]
Thanks, I didn't know that!!
