### ISSUE TITLE
lock-frontend dpkg

### ISSUE THREAD

**Issue by bxnyintuc** [rkaczorek/astroberry-server#99]
Can't get my Pi4 to recognize my zwo 224mc camera.  Assumed it is an update or driver issue. 
first hjappened after running sudo apt install indi-full gsc. "Is another process using it?" 
-removed 3 lock files
-verified dpkg
tired sudo dpkg --configure -a same error..."is locked by another process"
tried ps -A | grep apt
found 2 both synaptic pkexec and just synaptic
kiled them both
still same error

**Comment by rkaczorek** [comment]
I guess you ran updates just after booting. Let the system some time for unattended updates (security). Then you can do manual update
